render(){
    return(
      <div className="bodyDiv">
        <div className="titleDiv">
          <img className="logo" alt="logo" src={"mainlogo.png"}/>
          <p>Filler</p>
        </div>
        <div className="buttonDiv">
          <ButtonOne />
          <ButtonTwo />
        </div>
        <Background />
      </div>
    )
}

https://blog.hellojs.org/fetching-api-data-with-react-js-460fe8bbf8f2